title: "Levy Naibei"
email: levynaibei2@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This site displays the projects I got involved in while at MLH fellowship for Fall 2020
baseurl: "/" 
url: "/mlh-portfolio-web"
twitter_username: levynaibei2
github_username:  Levy-Naibei

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
